### ISSUE TITLE
math characters in plots yield warnings

### ISSUE THREAD

**Issue by tunesmith** [rubenv/jupyter-octave#2]
Hi, I'm trying to create a plot with a \theta character in the legends, but it creates warnings even though it successfully draws the character.

In the case of \theta, the error is:

> warning: text_renderer: skipping missing glyph for character '3b8'

It seems to happen with special characters in general. They get rendered, but spit out warnings. A simpler example which you can type into an Octave cell is:

`text(0.5, 0.5, 'Circle \010"')`

I've tried using the local Dockerfile as well as image published to github.

**Comment by rubenv** [comment]
This repo literally just packages Octave and Jupyter. What you describe
sounds like a bug in jupyter-octave, probably just best to file an issue
upstream.

**Comment by tunesmith** [comment]
Okay, thanks. I had earlier used octave with jupyter via `brew install octave` on the mac and thought I hadn't come across that output before. But I just learned I can use `warning off` to hide the warnings anyway. 

(It looks like the bug might have been https://savannah.gnu.org/bugs/?43651 which should be hitting mainline soon. )
